development:
  dialect: "postgres"
  database: {{envOr "POSTGRES_DB" "vigilate-dev"}}
  host: {{envOr "POSTGRES_HOST" "localhost"}}
  port: {{envOr "POSTGRES_PORT" "5432"}}
  user: {{envOr "POSTGRES_USERNAME" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "postgres"}}

production:
  dialect: "postgres"
  database: {{envOr "POSTGRES_DB" "vigilate"}}
  host: {{envOr "POSTGRES_HOST" "localhost"}}
  port: {{envOr "POSTGRES_PORT" "5432"}}
  user: {{envOr "POSTGRES_USERNAME" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "postgres"}}