development:
  dialect: "postgres"
  database: {{envOr "DEV_DB_NAME" "vigilate_development"}}
  host: {{envOr "DEV_DB_HOST" "127.0.0.1"}}
  port: {{envOr "DEV_DB_PORT" "5432"}}
  user: {{envOr "DB_USER_ACC" "postgres"}}
  password: {{envOr "DB_USER_PWD" "postgres"}}

production:
  dialect: "postgres"
  database: {{envOr "DB_NAME" "vigilate"}}
  host: {{envOr "DB_HOST" "127.0.0.1"}}
  port: {{envOr "DEV_DB_PORT" "5432"}}
  user: {{envOr "DB_USER_ACC" "postgres"}}
  password: {{envOr "DB_USER_PWD" "postgres"}}
